### ISSUE TITLE
关于HttpCode.Core需要使用安装VS2017才可以使用的问题

### ISSUE THREAD

**Issue by haishengXie0712** [stulzq/HttpCode.Core#2]
你好，我想了解一下为什么需要用VS2017才可以安装成功。而2015却不行，是安装HttpCode.Core时需要其他引用吗？因为VS2015已经包含了framework4.5了。对于之前的报错并不是很了解他报错的原因。谢谢

**Comment by stulzq** [comment]
该项目是 .net standard 2.0项目
