### ISSUE TITLE
更新一下 System.Drawing

### ISSUE THREAD

**Issue by closetao** [stulzq/HttpCode.Core#6]
NuGet安装提示：

> 无法解析依赖项“CoreCompat.System.Drawing.v2”

然后找到这个项目的主页[CoreCompat](https://github.com/CoreCompat/CoreCompat)
主页有说明：
> Good news! System.Drawing for .NET Core has been released as part of the Compatibility Pack for .NET Core.
> You can use  [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common)

所以是不是可以更新一下代码，去掉对`CoreCompat.System.Drawing.v2`的依赖，更改为：`System.Drawing.Common`，然后在NuGet上重新发布一下。多谢！

**Comment by stulzq** [comment]
本项目不再维护了，因为代码设计已经过时了。
